version: '3.3'

services:
  # elasticsearch_6.5.4:
  #   container_name: elasticsearch_6.5.4
  #   image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
  #   ports:
  #     - "9200:9200"
  #   environment:
  #     - discovery.type=single-node

  # elasticsearch_5.6.16:
  #   container_name: elasticsearch_5.6.16
  #   image: docker.elastic.co/elasticsearch/elasticsearch:5.6.16
  #   ports:
  #     - "9203:9200"
  #   environment:
  #     - discovery.type=single-nod
  #   volumes:
  #     - ./config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  #     - esdata:/usr/share/elasticsearch/data
  
  elasticsearch_2.3.5:
    image: elasticsearch:2.3.5
    container_name: elasticsearch_2.3.5
    ports:
      - "9202:9200"
    healthcheck:
      test: curl --silent --fail localhost:9200/_cluster/health || exit 1
      interval: 5s
      retries: 5
    volumes:
      - ./config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./config/elasticsearch/snapshot:/usr/share/elasticsearch/snapshot

  elasticsearch_1.7:
    image: pagarme/elasticsearch:1.7
    container_name: elasticsearch_1.7
    ports:
      - "9201:9200"
    healthcheck:
      test: curl --silent --fail localhost:9200/_cluster/health || exit 1
      interval: 5s
      retries: 5
    volumes:
      - ./config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./config/elasticsearch/snapshot:/usr/share/elasticsearch/snapshot

# volumes:
#   esdata:
#     driver: local